# Site settings
title: NamHyuk Ahn blog
email: 
description:
baseurl: ""
url: "http://nmhkahn.github.io"
twitter_username: 
github_username:  nmhkahn

# Build settings
permalink: /:title
markdown: kramdown

kramdown:
    auto_ids: true
    input: GFM
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]